# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-lovelink}
      POSTGRES_PASSWORD: ${DB_PASS:-lovelinkpass}
      POSTGRES_DB: lovelink
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://lovelink:lovelinkpass@db:5432/lovelink
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret_123
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      AI_SERVICE_URL: http://ai_service:8000
    depends_on:
      - db
      - redis
    env_file: .env

  web:
    build: ./web
    ports:
      - "3001:80"
    depends_on:
      - backend

  admin:
    build: ./admin
    ports:
      - "3002:80"
    depends_on:
      - backend

  mobile:
    build: ./mobile
    ports:
      - "19000:19000"
      - "19001:19001"
    depends_on:
      - backend

  ai_service:
    build: ./ai_service
    ports:
      - "8000:8000"
    depends_on:
      - backend

volumes:
  pgdata: